// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameEnum.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GameEnum.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace game {
namespace enumeration {

namespace {

const ::google::protobuf::EnumDescriptor* RoleType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GameEnum_2eproto() {
  protobuf_AddDesc_GameEnum_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GameEnum.proto");
  GOOGLE_CHECK(file != NULL);
  RoleType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GameEnum_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_GameEnum_2eproto() {
}

void protobuf_AddDesc_GameEnum_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016GameEnum.proto\022\020game.enumeration*1\n\010Ro"
    "leType\022\013\n\007FIGHTER\020\001\022\n\n\006BOWMAN\020\002\022\014\n\010MAGIC"
    "IAN\020\003B&\n\024com.game.enumerationB\016GameEnumP"
    "rotos", 125);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GameEnum.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GameEnum_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GameEnum_2eproto {
  StaticDescriptorInitializer_GameEnum_2eproto() {
    protobuf_AddDesc_GameEnum_2eproto();
  }
} static_descriptor_initializer_GameEnum_2eproto_;
const ::google::protobuf::EnumDescriptor* RoleType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoleType_descriptor_;
}
bool RoleType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace enumeration
}  // namespace game

// @@protoc_insertion_point(global_scope)
