// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameInfo.proto

package com.game.info;

public final class GameInfoProtos {
  private GameInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoleInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required .game.enumeration.RoleType type = 2;
    /**
     * <code>required .game.enumeration.RoleType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .game.enumeration.RoleType type = 2;</code>
     */
    com.game.enumeration.GameEnumProtos.RoleType getType();
  }
  /**
   * Protobuf type {@code game.info.RoleInfo}
   */
  public static final class RoleInfo extends
      com.google.protobuf.GeneratedMessage
      implements RoleInfoOrBuilder {
    // Use RoleInfo.newBuilder() to construct.
    private RoleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoleInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoleInfo defaultInstance;
    public static RoleInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RoleInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.game.enumeration.GameEnumProtos.RoleType value = com.game.enumeration.GameEnumProtos.RoleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.info.GameInfoProtos.internal_static_game_info_RoleInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.info.GameInfoProtos.internal_static_game_info_RoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.info.GameInfoProtos.RoleInfo.class, com.game.info.GameInfoProtos.RoleInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<RoleInfo> PARSER =
        new com.google.protobuf.AbstractParser<RoleInfo>() {
      public RoleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoleInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .game.enumeration.RoleType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.game.enumeration.GameEnumProtos.RoleType type_;
    /**
     * <code>required .game.enumeration.RoleType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .game.enumeration.RoleType type = 2;</code>
     */
    public com.game.enumeration.GameEnumProtos.RoleType getType() {
      return type_;
    }

    private void initFields() {
      name_ = "";
      type_ = com.game.enumeration.GameEnumProtos.RoleType.FIGHTER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.info.GameInfoProtos.RoleInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.info.RoleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.info.GameInfoProtos.RoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.info.GameInfoProtos.internal_static_game_info_RoleInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.info.GameInfoProtos.internal_static_game_info_RoleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.info.GameInfoProtos.RoleInfo.class, com.game.info.GameInfoProtos.RoleInfo.Builder.class);
      }

      // Construct using com.game.info.GameInfoProtos.RoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.game.enumeration.GameEnumProtos.RoleType.FIGHTER;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.info.GameInfoProtos.internal_static_game_info_RoleInfo_descriptor;
      }

      public com.game.info.GameInfoProtos.RoleInfo getDefaultInstanceForType() {
        return com.game.info.GameInfoProtos.RoleInfo.getDefaultInstance();
      }

      public com.game.info.GameInfoProtos.RoleInfo build() {
        com.game.info.GameInfoProtos.RoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.info.GameInfoProtos.RoleInfo buildPartial() {
        com.game.info.GameInfoProtos.RoleInfo result = new com.game.info.GameInfoProtos.RoleInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.info.GameInfoProtos.RoleInfo) {
          return mergeFrom((com.game.info.GameInfoProtos.RoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.info.GameInfoProtos.RoleInfo other) {
        if (other == com.game.info.GameInfoProtos.RoleInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.info.GameInfoProtos.RoleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.info.GameInfoProtos.RoleInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required .game.enumeration.RoleType type = 2;
      private com.game.enumeration.GameEnumProtos.RoleType type_ = com.game.enumeration.GameEnumProtos.RoleType.FIGHTER;
      /**
       * <code>required .game.enumeration.RoleType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .game.enumeration.RoleType type = 2;</code>
       */
      public com.game.enumeration.GameEnumProtos.RoleType getType() {
        return type_;
      }
      /**
       * <code>required .game.enumeration.RoleType type = 2;</code>
       */
      public Builder setType(com.game.enumeration.GameEnumProtos.RoleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .game.enumeration.RoleType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.game.enumeration.GameEnumProtos.RoleType.FIGHTER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.info.RoleInfo)
    }

    static {
      defaultInstance = new RoleInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.info.RoleInfo)
  }

  public interface ItemInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 price = 2;
    /**
     * <code>optional int32 price = 2;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional int32 price = 2;</code>
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code game.info.ItemInfo}
   */
  public static final class ItemInfo extends
      com.google.protobuf.GeneratedMessage
      implements ItemInfoOrBuilder {
    // Use ItemInfo.newBuilder() to construct.
    private ItemInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemInfo defaultInstance;
    public static ItemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ItemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              price_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.info.GameInfoProtos.internal_static_game_info_ItemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.info.GameInfoProtos.internal_static_game_info_ItemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.info.GameInfoProtos.ItemInfo.class, com.game.info.GameInfoProtos.ItemInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemInfo> PARSER =
        new com.google.protobuf.AbstractParser<ItemInfo>() {
      public ItemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    /**
     * <code>optional int32 price = 2;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 price = 2;</code>
     */
    public int getPrice() {
      return price_;
    }

    private void initFields() {
      name_ = "";
      price_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, price_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.info.GameInfoProtos.ItemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.info.ItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.info.GameInfoProtos.ItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.info.GameInfoProtos.internal_static_game_info_ItemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.info.GameInfoProtos.internal_static_game_info_ItemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.info.GameInfoProtos.ItemInfo.class, com.game.info.GameInfoProtos.ItemInfo.Builder.class);
      }

      // Construct using com.game.info.GameInfoProtos.ItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.info.GameInfoProtos.internal_static_game_info_ItemInfo_descriptor;
      }

      public com.game.info.GameInfoProtos.ItemInfo getDefaultInstanceForType() {
        return com.game.info.GameInfoProtos.ItemInfo.getDefaultInstance();
      }

      public com.game.info.GameInfoProtos.ItemInfo build() {
        com.game.info.GameInfoProtos.ItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.info.GameInfoProtos.ItemInfo buildPartial() {
        com.game.info.GameInfoProtos.ItemInfo result = new com.game.info.GameInfoProtos.ItemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.info.GameInfoProtos.ItemInfo) {
          return mergeFrom((com.game.info.GameInfoProtos.ItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.info.GameInfoProtos.ItemInfo other) {
        if (other == com.game.info.GameInfoProtos.ItemInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.info.GameInfoProtos.ItemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.info.GameInfoProtos.ItemInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 price = 2;
      private int price_ ;
      /**
       * <code>optional int32 price = 2;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.info.ItemInfo)
    }

    static {
      defaultInstance = new ItemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.info.ItemInfo)
  }

  public interface GameInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .game.info.RoleInfo roleInfo = 1;
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    java.util.List<com.game.info.GameInfoProtos.RoleInfo> 
        getRoleInfoList();
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    com.game.info.GameInfoProtos.RoleInfo getRoleInfo(int index);
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    int getRoleInfoCount();
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    java.util.List<? extends com.game.info.GameInfoProtos.RoleInfoOrBuilder> 
        getRoleInfoOrBuilderList();
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    com.game.info.GameInfoProtos.RoleInfoOrBuilder getRoleInfoOrBuilder(
        int index);

    // repeated .game.info.ItemInfo itemInfo = 2;
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    java.util.List<com.game.info.GameInfoProtos.ItemInfo> 
        getItemInfoList();
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    com.game.info.GameInfoProtos.ItemInfo getItemInfo(int index);
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    int getItemInfoCount();
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    java.util.List<? extends com.game.info.GameInfoProtos.ItemInfoOrBuilder> 
        getItemInfoOrBuilderList();
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    com.game.info.GameInfoProtos.ItemInfoOrBuilder getItemInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code game.info.GameInfo}
   */
  public static final class GameInfo extends
      com.google.protobuf.GeneratedMessage
      implements GameInfoOrBuilder {
    // Use GameInfo.newBuilder() to construct.
    private GameInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameInfo defaultInstance;
    public static GameInfo getDefaultInstance() {
      return defaultInstance;
    }

    public GameInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                roleInfo_ = new java.util.ArrayList<com.game.info.GameInfoProtos.RoleInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              roleInfo_.add(input.readMessage(com.game.info.GameInfoProtos.RoleInfo.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                itemInfo_ = new java.util.ArrayList<com.game.info.GameInfoProtos.ItemInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              itemInfo_.add(input.readMessage(com.game.info.GameInfoProtos.ItemInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          roleInfo_ = java.util.Collections.unmodifiableList(roleInfo_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          itemInfo_ = java.util.Collections.unmodifiableList(itemInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.info.GameInfoProtos.internal_static_game_info_GameInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.info.GameInfoProtos.internal_static_game_info_GameInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.info.GameInfoProtos.GameInfo.class, com.game.info.GameInfoProtos.GameInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<GameInfo> PARSER =
        new com.google.protobuf.AbstractParser<GameInfo>() {
      public GameInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameInfo> getParserForType() {
      return PARSER;
    }

    // repeated .game.info.RoleInfo roleInfo = 1;
    public static final int ROLEINFO_FIELD_NUMBER = 1;
    private java.util.List<com.game.info.GameInfoProtos.RoleInfo> roleInfo_;
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    public java.util.List<com.game.info.GameInfoProtos.RoleInfo> getRoleInfoList() {
      return roleInfo_;
    }
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    public java.util.List<? extends com.game.info.GameInfoProtos.RoleInfoOrBuilder> 
        getRoleInfoOrBuilderList() {
      return roleInfo_;
    }
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    public int getRoleInfoCount() {
      return roleInfo_.size();
    }
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    public com.game.info.GameInfoProtos.RoleInfo getRoleInfo(int index) {
      return roleInfo_.get(index);
    }
    /**
     * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
     */
    public com.game.info.GameInfoProtos.RoleInfoOrBuilder getRoleInfoOrBuilder(
        int index) {
      return roleInfo_.get(index);
    }

    // repeated .game.info.ItemInfo itemInfo = 2;
    public static final int ITEMINFO_FIELD_NUMBER = 2;
    private java.util.List<com.game.info.GameInfoProtos.ItemInfo> itemInfo_;
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    public java.util.List<com.game.info.GameInfoProtos.ItemInfo> getItemInfoList() {
      return itemInfo_;
    }
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    public java.util.List<? extends com.game.info.GameInfoProtos.ItemInfoOrBuilder> 
        getItemInfoOrBuilderList() {
      return itemInfo_;
    }
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    public int getItemInfoCount() {
      return itemInfo_.size();
    }
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    public com.game.info.GameInfoProtos.ItemInfo getItemInfo(int index) {
      return itemInfo_.get(index);
    }
    /**
     * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
     */
    public com.game.info.GameInfoProtos.ItemInfoOrBuilder getItemInfoOrBuilder(
        int index) {
      return itemInfo_.get(index);
    }

    private void initFields() {
      roleInfo_ = java.util.Collections.emptyList();
      itemInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getRoleInfoCount(); i++) {
        if (!getRoleInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getItemInfoCount(); i++) {
        if (!getItemInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < roleInfo_.size(); i++) {
        output.writeMessage(1, roleInfo_.get(i));
      }
      for (int i = 0; i < itemInfo_.size(); i++) {
        output.writeMessage(2, itemInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < roleInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, roleInfo_.get(i));
      }
      for (int i = 0; i < itemInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, itemInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.info.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.info.GameInfoProtos.GameInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.info.GameInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.info.GameInfoProtos.GameInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.info.GameInfoProtos.internal_static_game_info_GameInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.info.GameInfoProtos.internal_static_game_info_GameInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.info.GameInfoProtos.GameInfo.class, com.game.info.GameInfoProtos.GameInfo.Builder.class);
      }

      // Construct using com.game.info.GameInfoProtos.GameInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoleInfoFieldBuilder();
          getItemInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (roleInfoBuilder_ == null) {
          roleInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          roleInfoBuilder_.clear();
        }
        if (itemInfoBuilder_ == null) {
          itemInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.info.GameInfoProtos.internal_static_game_info_GameInfo_descriptor;
      }

      public com.game.info.GameInfoProtos.GameInfo getDefaultInstanceForType() {
        return com.game.info.GameInfoProtos.GameInfo.getDefaultInstance();
      }

      public com.game.info.GameInfoProtos.GameInfo build() {
        com.game.info.GameInfoProtos.GameInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.info.GameInfoProtos.GameInfo buildPartial() {
        com.game.info.GameInfoProtos.GameInfo result = new com.game.info.GameInfoProtos.GameInfo(this);
        int from_bitField0_ = bitField0_;
        if (roleInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            roleInfo_ = java.util.Collections.unmodifiableList(roleInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.roleInfo_ = roleInfo_;
        } else {
          result.roleInfo_ = roleInfoBuilder_.build();
        }
        if (itemInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            itemInfo_ = java.util.Collections.unmodifiableList(itemInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.itemInfo_ = itemInfo_;
        } else {
          result.itemInfo_ = itemInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.info.GameInfoProtos.GameInfo) {
          return mergeFrom((com.game.info.GameInfoProtos.GameInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.info.GameInfoProtos.GameInfo other) {
        if (other == com.game.info.GameInfoProtos.GameInfo.getDefaultInstance()) return this;
        if (roleInfoBuilder_ == null) {
          if (!other.roleInfo_.isEmpty()) {
            if (roleInfo_.isEmpty()) {
              roleInfo_ = other.roleInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoleInfoIsMutable();
              roleInfo_.addAll(other.roleInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.roleInfo_.isEmpty()) {
            if (roleInfoBuilder_.isEmpty()) {
              roleInfoBuilder_.dispose();
              roleInfoBuilder_ = null;
              roleInfo_ = other.roleInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              roleInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoleInfoFieldBuilder() : null;
            } else {
              roleInfoBuilder_.addAllMessages(other.roleInfo_);
            }
          }
        }
        if (itemInfoBuilder_ == null) {
          if (!other.itemInfo_.isEmpty()) {
            if (itemInfo_.isEmpty()) {
              itemInfo_ = other.itemInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemInfoIsMutable();
              itemInfo_.addAll(other.itemInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.itemInfo_.isEmpty()) {
            if (itemInfoBuilder_.isEmpty()) {
              itemInfoBuilder_.dispose();
              itemInfoBuilder_ = null;
              itemInfo_ = other.itemInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemInfoFieldBuilder() : null;
            } else {
              itemInfoBuilder_.addAllMessages(other.itemInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRoleInfoCount(); i++) {
          if (!getRoleInfo(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getItemInfoCount(); i++) {
          if (!getItemInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.info.GameInfoProtos.GameInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.info.GameInfoProtos.GameInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .game.info.RoleInfo roleInfo = 1;
      private java.util.List<com.game.info.GameInfoProtos.RoleInfo> roleInfo_ =
        java.util.Collections.emptyList();
      private void ensureRoleInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          roleInfo_ = new java.util.ArrayList<com.game.info.GameInfoProtos.RoleInfo>(roleInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.info.GameInfoProtos.RoleInfo, com.game.info.GameInfoProtos.RoleInfo.Builder, com.game.info.GameInfoProtos.RoleInfoOrBuilder> roleInfoBuilder_;

      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public java.util.List<com.game.info.GameInfoProtos.RoleInfo> getRoleInfoList() {
        if (roleInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(roleInfo_);
        } else {
          return roleInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public int getRoleInfoCount() {
        if (roleInfoBuilder_ == null) {
          return roleInfo_.size();
        } else {
          return roleInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public com.game.info.GameInfoProtos.RoleInfo getRoleInfo(int index) {
        if (roleInfoBuilder_ == null) {
          return roleInfo_.get(index);
        } else {
          return roleInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder setRoleInfo(
          int index, com.game.info.GameInfoProtos.RoleInfo value) {
        if (roleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoleInfoIsMutable();
          roleInfo_.set(index, value);
          onChanged();
        } else {
          roleInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder setRoleInfo(
          int index, com.game.info.GameInfoProtos.RoleInfo.Builder builderForValue) {
        if (roleInfoBuilder_ == null) {
          ensureRoleInfoIsMutable();
          roleInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          roleInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder addRoleInfo(com.game.info.GameInfoProtos.RoleInfo value) {
        if (roleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoleInfoIsMutable();
          roleInfo_.add(value);
          onChanged();
        } else {
          roleInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder addRoleInfo(
          int index, com.game.info.GameInfoProtos.RoleInfo value) {
        if (roleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoleInfoIsMutable();
          roleInfo_.add(index, value);
          onChanged();
        } else {
          roleInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder addRoleInfo(
          com.game.info.GameInfoProtos.RoleInfo.Builder builderForValue) {
        if (roleInfoBuilder_ == null) {
          ensureRoleInfoIsMutable();
          roleInfo_.add(builderForValue.build());
          onChanged();
        } else {
          roleInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder addRoleInfo(
          int index, com.game.info.GameInfoProtos.RoleInfo.Builder builderForValue) {
        if (roleInfoBuilder_ == null) {
          ensureRoleInfoIsMutable();
          roleInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          roleInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder addAllRoleInfo(
          java.lang.Iterable<? extends com.game.info.GameInfoProtos.RoleInfo> values) {
        if (roleInfoBuilder_ == null) {
          ensureRoleInfoIsMutable();
          super.addAll(values, roleInfo_);
          onChanged();
        } else {
          roleInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder clearRoleInfo() {
        if (roleInfoBuilder_ == null) {
          roleInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          roleInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public Builder removeRoleInfo(int index) {
        if (roleInfoBuilder_ == null) {
          ensureRoleInfoIsMutable();
          roleInfo_.remove(index);
          onChanged();
        } else {
          roleInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public com.game.info.GameInfoProtos.RoleInfo.Builder getRoleInfoBuilder(
          int index) {
        return getRoleInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public com.game.info.GameInfoProtos.RoleInfoOrBuilder getRoleInfoOrBuilder(
          int index) {
        if (roleInfoBuilder_ == null) {
          return roleInfo_.get(index);  } else {
          return roleInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public java.util.List<? extends com.game.info.GameInfoProtos.RoleInfoOrBuilder> 
           getRoleInfoOrBuilderList() {
        if (roleInfoBuilder_ != null) {
          return roleInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(roleInfo_);
        }
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public com.game.info.GameInfoProtos.RoleInfo.Builder addRoleInfoBuilder() {
        return getRoleInfoFieldBuilder().addBuilder(
            com.game.info.GameInfoProtos.RoleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public com.game.info.GameInfoProtos.RoleInfo.Builder addRoleInfoBuilder(
          int index) {
        return getRoleInfoFieldBuilder().addBuilder(
            index, com.game.info.GameInfoProtos.RoleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .game.info.RoleInfo roleInfo = 1;</code>
       */
      public java.util.List<com.game.info.GameInfoProtos.RoleInfo.Builder> 
           getRoleInfoBuilderList() {
        return getRoleInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.info.GameInfoProtos.RoleInfo, com.game.info.GameInfoProtos.RoleInfo.Builder, com.game.info.GameInfoProtos.RoleInfoOrBuilder> 
          getRoleInfoFieldBuilder() {
        if (roleInfoBuilder_ == null) {
          roleInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.info.GameInfoProtos.RoleInfo, com.game.info.GameInfoProtos.RoleInfo.Builder, com.game.info.GameInfoProtos.RoleInfoOrBuilder>(
                  roleInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          roleInfo_ = null;
        }
        return roleInfoBuilder_;
      }

      // repeated .game.info.ItemInfo itemInfo = 2;
      private java.util.List<com.game.info.GameInfoProtos.ItemInfo> itemInfo_ =
        java.util.Collections.emptyList();
      private void ensureItemInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          itemInfo_ = new java.util.ArrayList<com.game.info.GameInfoProtos.ItemInfo>(itemInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.info.GameInfoProtos.ItemInfo, com.game.info.GameInfoProtos.ItemInfo.Builder, com.game.info.GameInfoProtos.ItemInfoOrBuilder> itemInfoBuilder_;

      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public java.util.List<com.game.info.GameInfoProtos.ItemInfo> getItemInfoList() {
        if (itemInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemInfo_);
        } else {
          return itemInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public int getItemInfoCount() {
        if (itemInfoBuilder_ == null) {
          return itemInfo_.size();
        } else {
          return itemInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public com.game.info.GameInfoProtos.ItemInfo getItemInfo(int index) {
        if (itemInfoBuilder_ == null) {
          return itemInfo_.get(index);
        } else {
          return itemInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder setItemInfo(
          int index, com.game.info.GameInfoProtos.ItemInfo value) {
        if (itemInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfoIsMutable();
          itemInfo_.set(index, value);
          onChanged();
        } else {
          itemInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder setItemInfo(
          int index, com.game.info.GameInfoProtos.ItemInfo.Builder builderForValue) {
        if (itemInfoBuilder_ == null) {
          ensureItemInfoIsMutable();
          itemInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder addItemInfo(com.game.info.GameInfoProtos.ItemInfo value) {
        if (itemInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfoIsMutable();
          itemInfo_.add(value);
          onChanged();
        } else {
          itemInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder addItemInfo(
          int index, com.game.info.GameInfoProtos.ItemInfo value) {
        if (itemInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfoIsMutable();
          itemInfo_.add(index, value);
          onChanged();
        } else {
          itemInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder addItemInfo(
          com.game.info.GameInfoProtos.ItemInfo.Builder builderForValue) {
        if (itemInfoBuilder_ == null) {
          ensureItemInfoIsMutable();
          itemInfo_.add(builderForValue.build());
          onChanged();
        } else {
          itemInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder addItemInfo(
          int index, com.game.info.GameInfoProtos.ItemInfo.Builder builderForValue) {
        if (itemInfoBuilder_ == null) {
          ensureItemInfoIsMutable();
          itemInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder addAllItemInfo(
          java.lang.Iterable<? extends com.game.info.GameInfoProtos.ItemInfo> values) {
        if (itemInfoBuilder_ == null) {
          ensureItemInfoIsMutable();
          super.addAll(values, itemInfo_);
          onChanged();
        } else {
          itemInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder clearItemInfo() {
        if (itemInfoBuilder_ == null) {
          itemInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public Builder removeItemInfo(int index) {
        if (itemInfoBuilder_ == null) {
          ensureItemInfoIsMutable();
          itemInfo_.remove(index);
          onChanged();
        } else {
          itemInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public com.game.info.GameInfoProtos.ItemInfo.Builder getItemInfoBuilder(
          int index) {
        return getItemInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public com.game.info.GameInfoProtos.ItemInfoOrBuilder getItemInfoOrBuilder(
          int index) {
        if (itemInfoBuilder_ == null) {
          return itemInfo_.get(index);  } else {
          return itemInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public java.util.List<? extends com.game.info.GameInfoProtos.ItemInfoOrBuilder> 
           getItemInfoOrBuilderList() {
        if (itemInfoBuilder_ != null) {
          return itemInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemInfo_);
        }
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public com.game.info.GameInfoProtos.ItemInfo.Builder addItemInfoBuilder() {
        return getItemInfoFieldBuilder().addBuilder(
            com.game.info.GameInfoProtos.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public com.game.info.GameInfoProtos.ItemInfo.Builder addItemInfoBuilder(
          int index) {
        return getItemInfoFieldBuilder().addBuilder(
            index, com.game.info.GameInfoProtos.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .game.info.ItemInfo itemInfo = 2;</code>
       */
      public java.util.List<com.game.info.GameInfoProtos.ItemInfo.Builder> 
           getItemInfoBuilderList() {
        return getItemInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.info.GameInfoProtos.ItemInfo, com.game.info.GameInfoProtos.ItemInfo.Builder, com.game.info.GameInfoProtos.ItemInfoOrBuilder> 
          getItemInfoFieldBuilder() {
        if (itemInfoBuilder_ == null) {
          itemInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.info.GameInfoProtos.ItemInfo, com.game.info.GameInfoProtos.ItemInfo.Builder, com.game.info.GameInfoProtos.ItemInfoOrBuilder>(
                  itemInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          itemInfo_ = null;
        }
        return itemInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:game.info.GameInfo)
    }

    static {
      defaultInstance = new GameInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.info.GameInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_info_RoleInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_info_RoleInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_info_ItemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_info_ItemInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_info_GameInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_info_GameInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016GameInfo.proto\022\tgame.info\032\016GameEnum.pr" +
      "oto\"B\n\010RoleInfo\022\014\n\004name\030\001 \002(\t\022(\n\004type\030\002 " +
      "\002(\0162\032.game.enumeration.RoleType\"\'\n\010ItemI" +
      "nfo\022\014\n\004name\030\001 \002(\t\022\r\n\005price\030\002 \001(\005\"X\n\010Game" +
      "Info\022%\n\010roleInfo\030\001 \003(\0132\023.game.info.RoleI" +
      "nfo\022%\n\010itemInfo\030\002 \003(\0132\023.game.info.ItemIn" +
      "foB\037\n\rcom.game.infoB\016GameInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_info_RoleInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_info_RoleInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_info_RoleInfo_descriptor,
              new java.lang.String[] { "Name", "Type", });
          internal_static_game_info_ItemInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_info_ItemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_info_ItemInfo_descriptor,
              new java.lang.String[] { "Name", "Price", });
          internal_static_game_info_GameInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_game_info_GameInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_info_GameInfo_descriptor,
              new java.lang.String[] { "RoleInfo", "ItemInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.enumeration.GameEnumProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
