// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameEnum.proto

package com.game.enumeration;

public final class GameEnumProtos {
  private GameEnumProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code game.enumeration.RoleType}
   */
  public enum RoleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FIGHTER = 1;</code>
     */
    FIGHTER(0, 1),
    /**
     * <code>BOWMAN = 2;</code>
     */
    BOWMAN(1, 2),
    /**
     * <code>MAGICIAN = 3;</code>
     */
    MAGICIAN(2, 3),
    ;

    /**
     * <code>FIGHTER = 1;</code>
     */
    public static final int FIGHTER_VALUE = 1;
    /**
     * <code>BOWMAN = 2;</code>
     */
    public static final int BOWMAN_VALUE = 2;
    /**
     * <code>MAGICIAN = 3;</code>
     */
    public static final int MAGICIAN_VALUE = 3;


    public final int getNumber() { return value; }

    public static RoleType valueOf(int value) {
      switch (value) {
        case 1: return FIGHTER;
        case 2: return BOWMAN;
        case 3: return MAGICIAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RoleType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
            public RoleType findValueByNumber(int number) {
              return RoleType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.enumeration.GameEnumProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final RoleType[] VALUES = values();

    public static RoleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RoleType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:game.enumeration.RoleType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016GameEnum.proto\022\020game.enumeration*1\n\010Ro" +
      "leType\022\013\n\007FIGHTER\020\001\022\n\n\006BOWMAN\020\002\022\014\n\010MAGIC" +
      "IAN\020\003B&\n\024com.game.enumerationB\016GameEnumP" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
